-- ============================================================
-- Migration: RLS policies + auth trigger
-- Applied: 2026-07-24
-- Note: hand-authored, not generated by drizzle-kit.
--       drizzle-kit manages table schema (schema.ts → push).
--       This file tracks all security config applied via MCP.
-- ============================================================

-- ─── Enable RLS ──────────────────────────────────────────────────────────────

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets  ENABLE ROW LEVEL SECURITY;

-- ─── profiles policies ───────────────────────────────────────────────────────

-- Students read their own row
CREATE POLICY "profiles: students read own"
  ON public.profiles FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = id);

-- Organizers read all rows (needed for scanner + admin lookup)
CREATE POLICY "profiles: organizers read all"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  );

-- Users update their own row
CREATE POLICY "profiles: update own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING  ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);

-- Organizers update any row (token revocation)
CREATE POLICY "profiles: organizers update all"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  );

-- Authenticated users insert their own profile row
-- (guard in verifyOtp action; primary creation is via the DB trigger below)
CREATE POLICY "profiles: insert own"
  ON public.profiles FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = id);

-- ─── events policies ─────────────────────────────────────────────────────────

CREATE POLICY "events: authenticated can read"
  ON public.events FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "events: organizers can insert"
  ON public.events FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  );

CREATE POLICY "events: organizers can update own"
  ON public.events FOR UPDATE
  TO authenticated
  USING  ((SELECT auth.uid()) = organizer_id)
  WITH CHECK ((SELECT auth.uid()) = organizer_id);

-- ─── tickets policies ────────────────────────────────────────────────────────

-- Students see their own tickets
CREATE POLICY "tickets: students read own"
  ON public.tickets FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- Organizers see all tickets (dashboard stats + scanner + offline guest list)
CREATE POLICY "tickets: organizers read all"
  ON public.tickets FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  );

-- Students insert their own tickets (RSVP)
CREATE POLICY "tickets: students insert own"
  ON public.tickets FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Organizers update tickets (online check-in + offline sync bulk update)
CREATE POLICY "tickets: organizers update"
  ON public.tickets FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.role = 'organizer'
    )
  );

-- ─── Auth trigger: auto-create profile on signup ─────────────────────────────
--
-- WHY SECURITY DEFINER:
--   auth.users inserts are performed by the supabase_auth_admin role, which
--   has no GRANT on public.profiles. SECURITY DEFINER causes the function to
--   run as its owner (postgres / superuser), bypassing the table-level
--   permission. search_path is locked to '' to prevent privilege escalation.
--   This is the documented Supabase pattern for auth-triggered profile creation.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, check_in_token)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    'student',
    gen_random_uuid()
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();
